In [22]:
import numpy as np
import pandas as pd
from pathlib import Path

In [23]:
train_df = pd.read_csv(Path('Resources/2019loans2.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans2.csv'))

In [24]:
train_df.head(10)

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,7000.0,0.1894,256.38,MORTGAGE,75000.0,Not Verified,n,28.62,0.0,2.0,...,87.5,0.0,0.0,352260.0,62666.0,35000.0,10000.0,N,N,low_risk
1,40000.0,0.1614,975.71,MORTGAGE,102000.0,Source Verified,n,11.72,2.0,0.0,...,0.0,0.0,0.0,294664.0,109911.0,9000.0,71044.0,N,N,low_risk
2,11000.0,0.2055,294.81,RENT,45000.0,Verified,n,37.25,1.0,3.0,...,7.7,0.0,0.0,92228.0,36007.0,33000.0,46328.0,N,N,low_risk
3,4000.0,0.1612,140.87,MORTGAGE,38000.0,Not Verified,n,42.89,1.0,0.0,...,100.0,0.0,0.0,284273.0,52236.0,13500.0,52017.0,N,N,low_risk
4,14000.0,0.1797,505.93,MORTGAGE,43000.0,Source Verified,n,22.16,1.0,0.0,...,25.0,0.0,0.0,120280.0,88147.0,33300.0,78680.0,N,N,low_risk
5,6000.0,0.0756,186.81,MORTGAGE,90500.0,Source Verified,n,23.48,0.0,0.0,...,0.0,0.0,0.0,88500.0,44170.0,24000.0,57000.0,N,N,low_risk
6,10500.0,0.2250,293.00,RENT,32000.0,Verified,n,16.09,0.0,1.0,...,0.0,0.0,0.0,22581.0,10228.0,10700.0,9481.0,N,N,low_risk
7,22000.0,0.0819,448.09,MORTGAGE,92000.0,Source Verified,n,22.87,0.0,0.0,...,66.7,0.0,0.0,390661.0,169942.0,27100.0,143033.0,N,N,low_risk
8,10625.0,0.2055,284.76,RENT,54100.0,Source Verified,n,15.53,0.0,2.0,...,25.0,0.0,0.0,35620.0,18590.0,16000.0,17620.0,N,N,low_risk
9,20000.0,0.2534,591.02,OWN,38000.0,Source Verified,n,19.68,0.0,0.0,...,66.7,0.0,0.0,32064.0,27811.0,23400.0,8664.0,N,N,low_risk

In [25]:
test_df.head(10)

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,40000.0,0.1033,856.40,RENT,128700.0,Source Verified,n,12.47,0.0,1.0,...,57.1,0.0,0.0,63915.0,49510.0,49400.0,14515.0,Y,N,low_risk
1,24450.0,0.1430,572.72,MORTGAGE,44574.0,Not Verified,n,15.05,0.0,1.0,...,0.0,0.0,0.0,136425.0,19439.0,15500.0,18925.0,N,N,low_risk
2,13500.0,0.1430,316.23,OWN,60000.0,Not Verified,n,28.72,0.0,0.0,...,0.0,0.0,0.0,82124.0,65000.0,5400.0,61724.0,Y,N,low_risk
3,10625.0,0.1774,268.31,RENT,60000.0,Verified,n,15.70,0.0,4.0,...,20.0,0.0,0.0,54855.0,50335.0,23200.0,26255.0,N,N,low_risk
4,6375.0,0.1862,232.46,RENT,60000.0,Source Verified,n,35.50,0.0,0.0,...,75.0,0.0,0.0,90445.0,56541.0,15300.0,72345.0,N,N,low_risk
5,15000.0,0.1102,491.23,MORTGAGE,45000.0,Source Verified,n,66.32,0.0,0.0,...,100.0,0.0,0.0,107958.0,86144.0,7500.0,98458.0,N,N,low_risk
6,12000.0,0.0702,370.64,MORTGAGE,81500.0,Source Verified,n,16.61,0.0,0.0,...,25.0,1.0,0.0,241476.0,35885.0,33700.0,36918.0,N,N,low_risk
7,4500.0,0.1308,151.80,RENT,95000.0,Source Verified,n,24.36,0.0,0.0,...,64.3,0.0,0.0,86099.0,59896.0,40600.0,35499.0,N,N,low_risk
8,8000.0,0.1033,259.38,MORTGAGE,50000.0,Not Verified,n,13.18,0.0,0.0,...,100.0,0.0,0.0,145248.0,20553.0,16000.0,6800.0,N,N,low_risk
9,40000.0,0.0646,1225.24,MORTGAGE,140000.0,Source Verified,n,16.38,0.0,0.0,...,11.1,0.0,0.0,615294.0,139627.0,106900.0,77485.0,N,N,low_risk

In [26]:
train_df.dtypes

loan_amnt                     float64
int_rate                      float64
installment                   float64
home_ownership                 object
annual_inc                    float64
                               ...
total_bc_limit                float64
total_il_high_credit_limit    float64
hardship_flag                  object
debt_settlement_flag           object
target                         object
Length: 84, dtype: object

In [27]:
test_df.dtypes

loan_amnt                     float64
int_rate                      float64
installment                   float64
home_ownership                 object
annual_inc                    float64
                               ...
total_bc_limit                float64
total_il_high_credit_limit    float64
hardship_flag                  object
debt_settlement_flag           object
target                         object
Length: 84, dtype: object

In [28]:
# Find null values for train
for column in train_df.columns:
    print(f"Column {column} has {train_df[column].isnull().sum()} null values")

Column loan_amnt has 0 null values
Column int_rate has 0 null values
Column installment has 0 null values
Column home_ownership has 0 null values
Column annual_inc has 0 null values
Column verification_status has 0 null values
Column pymnt_plan has 0 null values
Column dti has 0 null values
Column delinq_2yrs has 0 null values
Column inq_last_6mths has 0 null values
Column open_acc has 0 null values
Column pub_rec has 0 null values
Column revol_bal has 0 null values
Column total_acc has 0 null values
Column initial_list_status has 0 null values
Column out_prncp has 0 null values
Column out_prncp_inv has 0 null values
Column total_pymnt has 0 null values
Column total_pymnt_inv has 0 null values
Column total_rec_prncp has 0 null values
Column total_rec_int has 0 null values
Column total_rec_late_fee has 0 null values
Column recoveries has 0 null values
Column collection_recovery_fee has 0 null values
Column last_pymnt_amnt has 0 null values
Column collections_12_mths_ex_med has 0 null values
Column policy_code has 0 null values
Column application_type has 0 null values
Column acc_now_delinq has 0 null values
Column tot_coll_amt has 0 null values
Column tot_cur_bal has 0 null values
Column open_acc_6m has 0 null values
Column open_act_il has 0 null values
Column open_il_12m has 0 null values
Column open_il_24m has 0 null values
Column mths_since_rcnt_il has 0 null values
Column total_bal_il has 0 null values
Column il_util has 0 null values
Column open_rv_12m has 0 null values
Column open_rv_24m has 0 null values
Column max_bal_bc has 0 null values
Column all_util has 0 null values
Column total_rev_hi_lim has 0 null values
Column inq_fi has 0 null values
Column total_cu_tl has 0 null values
Column inq_last_12m has 0 null values
Column acc_open_past_24mths has 0 null values
Column avg_cur_bal has 0 null values
Column bc_open_to_buy has 0 null values
Column bc_util has 0 null values
Column chargeoff_within_12_mths has 0 null values
Column delinq_amnt has 0 null values
Column mo_sin_old_il_acct has 0 null values
Column mo_sin_old_rev_tl_op has 0 null values
Column mo_sin_rcnt_rev_tl_op has 0 null values
Column mo_sin_rcnt_tl has 0 null values
Column mort_acc has 0 null values
Column mths_since_recent_bc has 0 null values
Column mths_since_recent_inq has 0 null values
Column num_accts_ever_120_pd has 0 null values
Column num_actv_bc_tl has 0 null values
Column num_actv_rev_tl has 0 null values
Column num_bc_sats has 0 null values
Column num_bc_tl has 0 null values
Column num_il_tl has 0 null values
Column num_op_rev_tl has 0 null values
Column num_rev_accts has 0 null values
Column num_rev_tl_bal_gt_0 has 0 null values
Column num_sats has 0 null values
Column num_tl_120dpd_2m has 0 null values
Column num_tl_30dpd has 0 null values
Column num_tl_90g_dpd_24m has 0 null values
Column num_tl_op_past_12m has 0 null values
Column pct_tl_nvr_dlq has 0 null values
Column percent_bc_gt_75 has 0 null values
Column pub_rec_bankruptcies has 0 null values
Column tax_liens has 0 null values
Column tot_hi_cred_lim has 0 null values
Column total_bal_ex_mort has 0 null values
Column total_bc_limit has 0 null values
Column total_il_high_credit_limit has 0 null values
Column hardship_flag has 0 null values
Column debt_settlement_flag has 0 null values
Column target has 0 null values

In [29]:
# Find null values for test
for column in test_df.columns:
    print(f"Column {column} has {test_df[column].isnull().sum()} null values")

Column loan_amnt has 0 null values
Column int_rate has 0 null values
Column installment has 0 null values
Column home_ownership has 0 null values
Column annual_inc has 0 null values
Column verification_status has 0 null values
Column pymnt_plan has 0 null values
Column dti has 0 null values
Column delinq_2yrs has 0 null values
Column inq_last_6mths has 0 null values
Column open_acc has 0 null values
Column pub_rec has 0 null values
Column revol_bal has 0 null values
Column total_acc has 0 null values
Column initial_list_status has 0 null values
Column out_prncp has 0 null values
Column out_prncp_inv has 0 null values
Column total_pymnt has 0 null values
Column total_pymnt_inv has 0 null values
Column total_rec_prncp has 0 null values
Column total_rec_int has 0 null values
Column total_rec_late_fee has 0 null values
Column recoveries has 0 null values
Column collection_recovery_fee has 0 null values
Column last_pymnt_amnt has 0 null values
Column collections_12_mths_ex_med has 0 null values
Column policy_code has 0 null values
Column application_type has 0 null values
Column acc_now_delinq has 0 null values
Column tot_coll_amt has 0 null values
Column tot_cur_bal has 0 null values
Column open_acc_6m has 0 null values
Column open_act_il has 0 null values
Column open_il_12m has 0 null values
Column open_il_24m has 0 null values
Column mths_since_rcnt_il has 0 null values
Column total_bal_il has 0 null values
Column il_util has 0 null values
Column open_rv_12m has 0 null values
Column open_rv_24m has 0 null values
Column max_bal_bc has 0 null values
Column all_util has 0 null values
Column total_rev_hi_lim has 0 null values
Column inq_fi has 0 null values
Column total_cu_tl has 0 null values
Column inq_last_12m has 0 null values
Column acc_open_past_24mths has 0 null values
Column avg_cur_bal has 0 null values
Column bc_open_to_buy has 0 null values
Column bc_util has 0 null values
Column chargeoff_within_12_mths has 0 null values
Column delinq_amnt has 0 null values
Column mo_sin_old_il_acct has 0 null values
Column mo_sin_old_rev_tl_op has 0 null values
Column mo_sin_rcnt_rev_tl_op has 0 null values
Column mo_sin_rcnt_tl has 0 null values
Column mort_acc has 0 null values
Column mths_since_recent_bc has 0 null values
Column mths_since_recent_inq has 0 null values
Column num_accts_ever_120_pd has 0 null values
Column num_actv_bc_tl has 0 null values
Column num_actv_rev_tl has 0 null values
Column num_bc_sats has 0 null values
Column num_bc_tl has 0 null values
Column num_il_tl has 0 null values
Column num_op_rev_tl has 0 null values
Column num_rev_accts has 0 null values
Column num_rev_tl_bal_gt_0 has 0 null values
Column num_sats has 0 null values
Column num_tl_120dpd_2m has 0 null values
Column num_tl_30dpd has 0 null values
Column num_tl_90g_dpd_24m has 0 null values
Column num_tl_op_past_12m has 0 null values
Column pct_tl_nvr_dlq has 0 null values
Column percent_bc_gt_75 has 0 null values
Column pub_rec_bankruptcies has 0 null values
Column tax_liens has 0 null values
Column tot_hi_cred_lim has 0 null values
Column total_bal_ex_mort has 0 null values
Column total_bc_limit has 0 null values
Column total_il_high_credit_limit has 0 null values
Column hardship_flag has 0 null values
Column debt_settlement_flag has 0 null values
Column target has 0 null values

In [30]:
# Find duplicate entries train
print(f"Duplicate entries: {train_df.duplicated().sum()}")

Duplicate entries: 0

In [31]:
# Find duplicate entries test
print(f"Duplicate entries: {test_df.duplicated().sum()}")

Duplicate entries: 0

In [11]:
# Convert categorical data to numeric and separate target feature for training data

In [12]:
# Convert categorical data to numeric and separate target feature for testing data

In [13]:
# add missing dummy variables to testing set

In [14]:
# Train the Logistic Regression model on the unscaled data and print the model score

In [15]:
# Train a Random Forest Classifier model and print the model score

In [16]:
# Scale the data

In [17]:
# Train the Logistic Regression model on the scaled data and print the model score

In [18]:
# Train a Random Forest Classifier model on the scaled data and print the model score